services:
  duld:
    build:
      target: production
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${DULD_CONFIG_FILE}:/mnt/duld.yaml:ro
      - ${DULD_DRIVE_FILE}:/mnt/drive.yaml:ro
      - ${DULD_DRIVE_CONFIG_PATH}:/mnt/config:ro
      - ${DULD_DRIVE_DATA_PATH}:/mnt/data:rw
      - ${DULD_TM_PATH:-/tmp}:/mnt/tm:ro
      - ${DULD_HAH_PATH:-/tmp}:/mnt/hah:rw
    ports:
      - "${DULD_HOST}:${DULD_PORT}:80"
    environment:
      POETRY_CONFIG_DIR: /tmp
      POETRY_CACHE_DIR: /tmp
      DULD_UID: ${DULD_UID}
      DULD_GID: ${DULD_GID}
    logging:
      driver: journald
      options:
        tag: duld-duld
    command: /app/scripts/start.sh
