services:
  duld:
    build:
      target: production
    volumes:
      - ${DULD_CONFIG_FILE}:/mnt/duld.yaml:ro
      - ${DULD_DRIVE_FILE}:/mnt/drive.yaml:ro
      - ${DULD_DRIVE_CONFIG_PATH}:/mnt/config:ro
      - ${DULD_DRIVE_DATA_PATH}:/mnt/data:rw
      - ${DULD_LOG_PATH}:/mnt/log:rw
      - ${DULD_TM_PATH:-/tmp}:/mnt/tm:ro
      - ${DULD_HAH_PATH:-/tmp}:/mnt/hah:rw
    ports:
      - "${DULD_HOST}:${DULD_PORT}:80"
    extra_hosts:
      host.docker.internal: host-gateway
    environment:
      TZ: ${DULD_TZ:-}
      POETRY_CONFIG_DIR: /tmp
      POETRY_CACHE_DIR: /tmp
      DULD_UID: ${DULD_UID}
      DULD_GID: ${DULD_GID}
    command: /app/scripts/start.sh
